(deftheme pope
  "A light theme.")

(custom-theme-set-faces
 'pope
 '(bold ((t (:weight bold))))
 '(bold-italic ((t (:weight bold :slant italic))))
 '(cursor ((t (:background "red1"))))
 '(default ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(diff-added ((t :foreground "green4")))
 '(diff-changed ((t :foreground "orange1")))
 '(diff-removed ((t :foreground "red1")))
 '(diff-hunk-header ((t :weight bold)))
 '(diff-function ((t :foreground "orange1")))
 '(diff-header ((t :slant italic)))
 '(diff-file-header ((t :underline t)))
 '(eshell-prompt ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "SlateBlue1"))))
 '(font-lock-comment-delimiter-face ((t (:weight bold :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant italic :foreground "grey56"))))
 '(font-lock-constant-face ((t (:weight bold :foreground "orange1"))))
 '(font-lock-doc-face ((t (:weight bold :inherit (font-lock-comment-face)))))
 '(font-lock-function-name-face ((t (:weight bold :foreground "DodgerBlue4"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "DodgerBlue1"))))
 '(font-lock-negation-char-face ((t (:foreground "red1"))))
 '(font-lock-preprocessor-face ((t (:foreground "ForestGreen" :inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "LimeGreen" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-string-face ((t (:foreground "green4"))))
 '(font-lock-type-face ((t (:underline t))))
 '(font-lock-variable-name-face ((t (:foreground "red1"))))
 '(font-lock-warning-face ((t (:inverse-video t))))
 '(fringe ((t (:background "gainsboro"))))
 '(header-line ((t (:inverse-video t))))
 '(highlight ((t (:slant italic :underline "DodgerBlue1"))))
 '(hl-line ((t (:background "grey98"))))
 '(isearch ((t (:inherit (region)))))
 '(isearch-fail ((t (:foreground "red1"))))
 '(italic ((t (:slant italic))))
 '(lazy-highlight ((t (:background "LightYellow1"))))
 '(link ((t (:underline t :foreground "DodgerBlue1"))))
 '(link-visited ((t (:foreground "DodgerBlue4" :inherit (link)))))
 '(linum ((t (:foreground "grey56" :inherit (fringe)))))
 '(match ((t (:background "LightYellow1"))))
 '(magit-branch ((t (:foreground "DodgerBlue1" :background "LightCyan"))))
 '(magit-diff-add ((t (:inherit (diff-added)))))
 '(magit-diff-del ((t (:inherit (diff-removed)))))
 '(magit-diff-file-header  ((t (:inherit (magit-header diff-file-header)))))
 '(magit-diff-hunk-header ((t (:inherit (magit-header diff-hunk-header)))))
 '(magit-diff-none ((t (:inherit (diff-context)))))
 '(magit-item-highlight ((t (:background "grey94"))))
 '(magit-log-graph ((t :inherit (shadow))))
 '(magit-log-head-label-local ((t :foreground "red1" :inherit (magit-branch))))
 '(magit-log-head-label-local ((t :inherit (magit-branch))))
 '(magit-log-head-label-remote ((t :foreground "green4" :inherit (magit-branch))))
 '(magit-log-head-label-tags ((t :inherit (magit-log-tag-label))))
 '(magit-log-sha1 ((t :weight bold)))
 '(magit-log-tag-label ((t :foreground "orange1" :inherit (magit-branch))))
 '(magit-section-title ((t (:height 1.2 :slant italic))))
 '(minibuffer-prompt ((t (:background "LightYellow1"))))
 '(mode-line ((t (:box (:line-width 1 :color "grey56" :style nil) :background "grey95"))))
 '(mode-line-inactive ((t (:foreground "grey56" :background "grey95"))))
 '(mouse ((t (:foreground "#000000" :background "#FFFFFF"))))
 '(magit-item-mark ((t :foreground "orange1")))
 '(org-block ((t (:foreground "gbreen4"))))
 '(org-code ((t (:foreground "green4" :inherit (shadow)))))
 '(org-done ((t (:foreground "green4"))))
 '(org-hide ((t (:foreground "grey94"))))
 '(org-level-1 ((t (:height 1.6 :slant italic))))
 '(org-level-2 ((t (:height 1.3 :slant italic))))
 '(org-level-3 ((t (:height 1.2 :slant italic))))
 '(org-level-4 ((t (:height 1.1 :slant italic))))
 '(org-level-5 ((t (:height 1.1 :slant italic))))
 '(org-level-6 ((t (:height 1.1 :slant italic))))
 '(org-level-7 ((t (:height 1.1 :slant italic))))
 '(org-level-8 ((t (:height 1.1 :slant italic))))
 '(org-meta-line ((t (:foreground "grey56" :inherit (font-lock-comment-face)))))
 '(org-table ((((class color) (min-colors 88) (background light)) (:foreground "DodgerBlue4"))))
 '(org-tag ((t (:height 0.8 :weight bold :foreground "CadetBlue4"))))
 '(org-todo ((t (:foreground "red1"))))
 '(region ((t (:background "LightSkyBlue1"))))
 '(shadow ((t (:foreground "grey32"))))
 '(show-paren-match ((t (:inherit (region)))))
 '(show-paren-mismatch ((t (:background "red1"))))
 )

(provide-theme 'pope)
