"set background=light
"colo macvim
colorscheme ir_black

if has("mac")
  set gfn=Courier:h12
elseif has("unix")
  set gfn=Inconsolata\ Medium\ 12
else
  set guifont=Inconsolata:h11:cANSI
endif

set vb t_vb=
set guioptions=egmrLtTb
