set nocompatible

set autoindent
set backspace=indent,eol,start
set encoding=utf8
set expandtab
set foldmethod=marker
set hidden
set history=100
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set linebreak
set listchars=tab:▸\ ,eol:¬
set mouse=a
set number
set ruler
set shiftwidth=4
set smartcase
set smartindent
set softtabstop=4
set tabstop=4
set textwidth=0
set ttymouse=xterm2
set visualbell
set t_vb=
set wildmenu
set colorcolumn=80

au BufRead,BufNewFile * match ErrorMsg  /[ \t]\+$/
"au BufRead,BufNewFile * match ErrorMsg   /\%>80v.\+/

" Things to think about when using xterm
if has("xterm_clipboard")
    behave xterm
    set t_Co=256
else
    set t_Co=16
    set paste
    set clipboard+=unnamed
endif

let g:ctrlp_working_path_mode='ra'

execute pathogen#infect()

let s:host_vimrc = $HOME . '/.' . hostname() . '.vimrc'
if filereadable(s:host_vimrc)
    execute 'source ' . s:host_vimrc
endif

syntax on
filetype plugin on
filetype indent on
