set nocompatible

set autoindent
set backspace=indent,eol,start
set encoding=utf8
set expandtab
set foldmethod=marker
set hidden
set history=100
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set linebreak
set fillchars+=vert:\|  " add a bar for vertical splits
set list
set listchars=tab:»·,nbsp:+,trail:·,extends:→,precedes:←,eol:¬
set mouse=a
set number
set ruler
set shiftwidth=4
set smartcase
set smartindent
set softtabstop=4
set tabstop=4
set textwidth=0
if !has('nvim')
    set ttymouse=xterm2
endif
set visualbell
set t_vb=
set wildmenu
set colorcolumn=80
set splitbelow splitright

au BufRead,BufNewFile * match ErrorMsg  /[ \t]\+$/
"au BufRead,BufNewFile * match ErrorMsg   /\%>80v.\+/

if !has('gui_running') && &term =~ '^\%(screen\|tmux\)'
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif


" Things to think about when using xterm
if has("xterm_clipboard")
    behave xterm
    set t_Co=256
else
    set t_Co=16
    set paste
    set clipboard+=unnamed
endif

let g:ctrlp_working_path_mode='ra'
let g:javascript_plugin_jsdoc = 1

execute pathogen#infect()

if exists('$BASE16_THEME')
      \ && (!exists('g:colors_name') || g:colors_name != 'base16-$BASE16_THEME')
    let base16colorspace=256
    colorscheme base16-$BASE16_THEME
endif

if filereadable(expand("~/.vimrc_background"))
    let base16colorspace=256
    source ~/.vimrc_background
    "autocmd! ColorScheme * hi VertSplit ctermbg=none
endif

let s:host_vimrc = $HOME . '/.' . hostname() . '.vimrc'
if filereadable(s:host_vimrc)
    execute 'source ' . s:host_vimrc
endif

syntax on
filetype plugin on
filetype indent on
