# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}:
{
  artcnn = {
    pname = "artcnn";
    version = "v1.4.1";
    src = fetchFromGitHub {
      owner = "Artoriuz";
      repo = "ArtCNN";
      rev = "v1.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-hJBJya8Xmr/Lx1iUNFsZjs6cmXrAlPxaJx2X1WRX5AY=";
    };
  };
  fish-catppuccin = {
    pname = "fish-catppuccin";
    version = "6a85af2ff722ad0f9fbc8424ea0a5c454661dfed";
    src = fetchgit {
      url = "https://github.com/catppuccin/fish";
      rev = "6a85af2ff722ad0f9fbc8424ea0a5c454661dfed";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Oc0emnIUI4LV7QJLs4B2/FQtCFewRFVp7EDv8GawFsA=";
    };
    date = "2025-03-01";
  };
  fish-rose-pine = {
    pname = "fish-rose-pine";
    version = "b82982c55582cfaf6f220de1893c7c73dd0cb301";
    src = fetchgit {
      url = "https://github.com/rose-pine/fish";
      rev = "b82982c55582cfaf6f220de1893c7c73dd0cb301";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Dvaw1k7XOU2NUQbTJAXPgAOPN1zTLVrc7NZDY5/KHeM=";
    };
    date = "2025-05-06";
  };
  fish-tokyonight = {
    pname = "fish-tokyonight";
    version = "v4.8.0";
    src = fetchFromGitHub {
      owner = "vitallium";
      repo = "tokyonight-fish";
      rev = "v4.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-JI1kTez4CeMpSKcSikFUee15N48zkJJOvLHCi0H2PUc=";
    };
  };
  hatsune-miku-cursor = {
    pname = "hatsune-miku-cursor";
    version = "1.2.6";
    src = fetchFromGitHub {
      owner = "supermariofps";
      repo = "hatsune-miku-windows-linux-cursors";
      rev = "1.2.6";
      fetchSubmodules = false;
      sha256 = "sha256-OQjjOc9VnxJ7tWNmpHIMzNWX6WsavAOkgPwK1XAMwtE=";
    };
  };
  ia-writer = {
    pname = "ia-writer";
    version = "f32c04c3058a75d7ce28919ce70fe8800817491b";
    src = fetchgit {
      url = "https://github.com/iaolo/iA-Fonts";
      rev = "f32c04c3058a75d7ce28919ce70fe8800817491b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-2T165nFfCzO65/PIHauJA//S+zug5nUwPcg8NUEydfc=";
    };
    date = "2023-06-16";
  };
  iqm = {
    pname = "iqm";
    version = "8554dca2b86dc3845981fad6758d3829ce0d4a56";
    src = fetchgit {
      url = "https://github.com/lsalzman/iqm";
      rev = "8554dca2b86dc3845981fad6758d3829ce0d4a56";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-zR3AdHg0f2g14ZHVgTREYheXcHr6evnZxP3HEo7byRI=";
    };
    date = "2025-07-24";
  };
  ocenaudio-bin = {
    pname = "ocenaudio-bin";
    version = "3.16.1";
    src = fetchurl {
      url = "https://www.ocenaudio.com/downloads/index.php/ocenaudio_universal.dmg?version=v3.16.1";
      sha256 = "sha256-vJ9wszLcPvSNeuGhff4Ug3lCG3B5Qyvqf6Ht4BMy8X0=";
    };
  };
  p5r-grub = {
    pname = "p5r-grub";
    version = "v1.0";
    src = fetchFromGitHub {
      owner = "SiriusAhu";
      repo = "Persona_5_Royal_Grub_Themes";
      rev = "v1.0";
      fetchSubmodules = false;
      sha256 = "sha256-YnTBgUWWsR0W8eTtg3oa2MIXSqj7HW555xSEhV7/74w=";
    };
  };
  prchann-font-collection = {
    pname = "prchann-font-collection";
    version = "e99955f794eb1f1375a5cb677d129758f51cbc3d";
    src = fetchgit {
      url = "https://github.com/prchann/fonts";
      rev = "e99955f794eb1f1375a5cb677d129758f51cbc3d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-GlfGnaXNdvTLpwEssxzPyJwclgVi6iNp8hEGuy/rC5o=";
    };
    date = "2022-09-02";
  };
  sf-mono-font = {
    pname = "sf-mono-font";
    version = "1409ae79074d204c284507fef9e479248d5367c1";
    src = fetchgit {
      url = "https://github.com/supercomputra/SF-Mono-Font";
      rev = "1409ae79074d204c284507fef9e479248d5367c1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-3wG3M4Qep7MYjktzX9u8d0iDWa17FSXYnObSoTG2I/o=";
    };
    date = "2018-06-08";
  };
  sf-mono-nf-liga = {
    pname = "sf-mono-nf-liga";
    version = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
    src = fetchgit {
      url = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized";
      rev = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AYjKrVLISsJWXN6Cj74wXmbJtREkFDYOCRw1t2nVH2w=";
    };
    date = "2023-07-01";
  };
  shflags = {
    pname = "shflags";
    version = "v1.3.0";
    src = fetchFromGitHub {
      owner = "kward";
      repo = "shflags";
      rev = "v1.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-qOFPSYglb6p8GxagXVHdJW2namUCxi3REuR55On8QEo=";
    };
  };
}
