test-key: ENC[AES256_GCM,data:O2bg9E0owNGt1VDklAekXA==,iv:YJ6HhppN09DRlXY4z/V8C+hyUZ6bYI2QNQuQrymfcq8=,tag:jbtuNLVJSsFi5DZgxqR6Gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ln33jd2r422sf9ncryve4qv2yhp7l5w6h6nahmyxe667p0sn25pqcunuje
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMFVXMTF6dzRta1cvWWYr
            MXJkNVB1MVRMR0ZzT2FidmQ1Tmg1Vi9qakhVCkhNU3BSbkM0ZmFnRE5ZQWsyRWdY
            TU0vMUNWRXF5UW4xSlNiUmJySjU1anMKLS0tIGZNZElITnNnOTZTY2pnaFptLzhM
            aFlZSVJrbkpIZXJoTDBiQTVtZzNFVGsKwE23Ip+qMEVOQgopTRZquaDgmxDs2plh
            0roWL/5XNRIkURR46c+W9Owr6Uf4vyIQfr3Ipyk6GQIfcfnv0tP6WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-30T07:14:20Z"
    mac: ENC[AES256_GCM,data:Po6SI6fHLpCwVnYJKtin0IuEPLYkYpUGdbMjROR6sHTx7n/ru24AjkJO6EjmPCdHkp3CCOl5AEu/cRF9TL/vVlweupwXLnzsaM0+z3WTjvS75OnxNKpAOFjNRs6P3MZswCvHpO/16mm6fAfWtg19/egOuVyq+tCtqryJjZPoKV0=,iv:texZxMYN9r+Yew3rO3D6FE9CFTtRRC0cd2jyp+D98tQ=,tag:aa4PC2p7N6RJYwAcxwvkUA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
