test-key: ENC[AES256_GCM,data:O2bg9E0owNGt1VDklAekXA==,iv:YJ6HhppN09DRlXY4z/V8C+hyUZ6bYI2QNQuQrymfcq8=,tag:jbtuNLVJSsFi5DZgxqR6Gw==,type:str]
vyprvpn-auth-user-pass: ENC[AES256_GCM,data:7IhsayUz4q9i1NaN9opkeLf81o7AmTyxyWqjkf+Yi3qO5aQM,iv:UlZ4Ae10h2l1LVvQkpt0bjDh3F7U9xmvEvWAyA/OkBA=,tag:0WJsvFHaKb9S2p7VkcbTuw==,type:str]
tailscale-auth-key: ENC[AES256_GCM,data:CIUtduyM2jObumDwH5pBKx25uBzf5EPfkUsBMbTfagMR2Dmp9Z27+OQwIjvWKiVbWboV4yx2A7ndgUjtme0=,iv:thXaziu8UCUPgv2si7MgEN21BQ9S9fCwq/Us/WMKPds=,tag:IuBhpDFH3yIIBFc5hDqfaQ==,type:str]
sops:
    age:
        - recipient: age1ln33jd2r422sf9ncryve4qv2yhp7l5w6h6nahmyxe667p0sn25pqcunuje
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMFVXMTF6dzRta1cvWWYr
            MXJkNVB1MVRMR0ZzT2FidmQ1Tmg1Vi9qakhVCkhNU3BSbkM0ZmFnRE5ZQWsyRWdY
            TU0vMUNWRXF5UW4xSlNiUmJySjU1anMKLS0tIGZNZElITnNnOTZTY2pnaFptLzhM
            aFlZSVJrbkpIZXJoTDBiQTVtZzNFVGsKwE23Ip+qMEVOQgopTRZquaDgmxDs2plh
            0roWL/5XNRIkURR46c+W9Owr6Uf4vyIQfr3Ipyk6GQIfcfnv0tP6WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T04:11:16Z"
    mac: ENC[AES256_GCM,data:msN5ZKjyV1bwOZ41iFMPNDBusSy030q21i37roTMv15t05Fx/6ltG23A+F81asPOlqpEIFcqeb8+9zzB/jqOZq6qlilPkamRqIfVh1pd/8aQWbIpNzrZEf4SPQD/MdfiARlVfSVFF8bV/gCpa+akUz+uLu2VWw6XSKK+BGJLZDY=,iv:HmYhPmZFzCh9yNO3By37FkElMfcTRUOi0+Z0Je5/kpk=,tag:G5C08TmcA9aiS/0Frxp3kw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
