test-key: ENC[AES256_GCM,data:O2bg9E0owNGt1VDklAekXA==,iv:YJ6HhppN09DRlXY4z/V8C+hyUZ6bYI2QNQuQrymfcq8=,tag:jbtuNLVJSsFi5DZgxqR6Gw==,type:str]
vyprvpn-auth-user-pass: ENC[AES256_GCM,data:7IhsayUz4q9i1NaN9opkeLf81o7AmTyxyWqjkf+Yi3qO5aQM,iv:UlZ4Ae10h2l1LVvQkpt0bjDh3F7U9xmvEvWAyA/OkBA=,tag:0WJsvFHaKb9S2p7VkcbTuw==,type:str]
tailscale-auth-key: ENC[AES256_GCM,data:CIUtduyM2jObumDwH5pBKx25uBzf5EPfkUsBMbTfagMR2Dmp9Z27+OQwIjvWKiVbWboV4yx2A7ndgUjtme0=,iv:thXaziu8UCUPgv2si7MgEN21BQ9S9fCwq/Us/WMKPds=,tag:IuBhpDFH3yIIBFc5hDqfaQ==,type:str]
syncthing-password: ENC[AES256_GCM,data:2JVBreTuTF4W92DY8nW4qUevKPwYBghpRbiITYcTx9bmI8iCTqbL0/XwHUGKBV4xI+TcexsVkujhxYBP,iv:xWTyn68SpmiIBkN6Q9Ie6U9d68yImL4O6iRz7tC18p4=,tag:+GQdGH+ifiLw4WcgaEgvzg==,type:str]
sops:
    age:
        - recipient: age1ln33jd2r422sf9ncryve4qv2yhp7l5w6h6nahmyxe667p0sn25pqcunuje
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMFVXMTF6dzRta1cvWWYr
            MXJkNVB1MVRMR0ZzT2FidmQ1Tmg1Vi9qakhVCkhNU3BSbkM0ZmFnRE5ZQWsyRWdY
            TU0vMUNWRXF5UW4xSlNiUmJySjU1anMKLS0tIGZNZElITnNnOTZTY2pnaFptLzhM
            aFlZSVJrbkpIZXJoTDBiQTVtZzNFVGsKwE23Ip+qMEVOQgopTRZquaDgmxDs2plh
            0roWL/5XNRIkURR46c+W9Owr6Uf4vyIQfr3Ipyk6GQIfcfnv0tP6WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-22T03:47:43Z"
    mac: ENC[AES256_GCM,data:CZi1axxT9Zkiobr1v1DzoitNceVhwhra3w48ln18oAC08VNmAbxpX3VYQytaH3A1Fi5iFckB4g8AREH1Vv7cZ/mVym4MFEQgaxWLTatfxtEkuBTlA+2d34oGuQUFecP3sGzAhN3uv6ByzZjd93ZKTvp2hRtK3NuvG3Pb+ViN7eI=,iv:daX2Dt/ODbJxpzy5QweRKQtT/ufSV+5vKreZZbUF2hw=,tag:mkMaoY2RSrld7SRHLHr5SA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
