test-key: ENC[AES256_GCM,data:O2bg9E0owNGt1VDklAekXA==,iv:YJ6HhppN09DRlXY4z/V8C+hyUZ6bYI2QNQuQrymfcq8=,tag:jbtuNLVJSsFi5DZgxqR6Gw==,type:str]
vyprvpn-auth-user-pass: ENC[AES256_GCM,data:7IhsayUz4q9i1NaN9opkeLf81o7AmTyxyWqjkf+Yi3qO5aQM,iv:UlZ4Ae10h2l1LVvQkpt0bjDh3F7U9xmvEvWAyA/OkBA=,tag:0WJsvFHaKb9S2p7VkcbTuw==,type:str]
sops:
    age:
        - recipient: age1ln33jd2r422sf9ncryve4qv2yhp7l5w6h6nahmyxe667p0sn25pqcunuje
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMFVXMTF6dzRta1cvWWYr
            MXJkNVB1MVRMR0ZzT2FidmQ1Tmg1Vi9qakhVCkhNU3BSbkM0ZmFnRE5ZQWsyRWdY
            TU0vMUNWRXF5UW4xSlNiUmJySjU1anMKLS0tIGZNZElITnNnOTZTY2pnaFptLzhM
            aFlZSVJrbkpIZXJoTDBiQTVtZzNFVGsKwE23Ip+qMEVOQgopTRZquaDgmxDs2plh
            0roWL/5XNRIkURR46c+W9Owr6Uf4vyIQfr3Ipyk6GQIfcfnv0tP6WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-08T05:14:23Z"
    mac: ENC[AES256_GCM,data:7bEM3gOnYa6PTeFEH/Hw1jFqG1nZMe/1gIlqd15z8cD1B5cVNJLh9ljv6c2eog9lM3kgxjeevh1dwHHMs4U9AHnN6JG3XXiJCWr3DIyh3452q5FJuZE9HUCLADO4anviYpnwYVBRNj1UhR8vYFqR/jE6/CCLEDh0nHT0VHLkwqU=,iv:AvhIygGbNc8UCAi7Cg12nbAK7ReUr7Gd27KQXvUnlVE=,tag:WJHcVJmAuv7fWGHNXEbqVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
