[fish-rose-pine]
src.git = "https://github.com/rose-pine/fish"
fetch.git = "https://github.com/rose-pine/fish"

[fish-catppuccin]
src.git = "https://github.com/catppuccin/fish"
fetch.git = "https://github.com/catppuccin/fish"

[fish-tokyonight]
src.github_tag = "vitallium/tokyonight-fish"
fetch.github = "vitallium/tokyonight-fish"

[p5r-grub]
src.github_tag = "SiriusAhu/Persona_5_Royal_Grub_Themes"
fetch.github = "SiriusAhu/Persona_5_Royal_Grub_Themes"

[rbutil]
src.manual = "1.5.1"
fetch.url = "https://git.rockbox.org/cgit/rockbox.git/snapshot/rockbox-rbutil_$ver.tar.gz"

[shflags]
src.github_tag = "kward/shflags"
fetch.github = "kward/shflags"

[iqm]
src.git = "https://github.com/lsalzman/iqm"
fetch.git = "https://github.com/lsalzman/iqm"

[hatsune-miku-cursor]
src.git = "https://github.com/supermariofps/hatsune-miku-windows-linux-cursors"
fetch.git = "https://github.com/supermariofps/hatsune-miku-windows-linux-cursors"

[artcnn]
src.github_tag = "Artoriuz/ArtCNN"
fetch.github = "Artoriuz/ArtCNN"

# Fonts

[ia-writer]
src.git = "https://github.com/iaolo/iA-Fonts"
fetch.git = "https://github.com/iaolo/iA-Fonts"

[sf-mono-font]
src.git = "https://github.com/supercomputra/SF-Mono-Font"
fetch.git = "https://github.com/supercomputra/SF-Mono-Font"

[sf-mono-nf-liga]
src.git = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized"
fetch.git = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized"

[prchann-font-collection]
src.git = "https://github.com/prchann/fonts"
fetch.git = "https://github.com/prchann/fonts"
