[fish-rose-pine]
src.git = "https://github.com/rose-pine/fish"
fetch.git = "https://github.com/rose-pine/fish"

[fish-catppuccin]
src.git = "https://github.com/catppuccin/fish"
fetch.git = "https://github.com/catppuccin/fish"

[fish-tokyonight]
src.github_tag = "vitallium/tokyonight-fish"
fetch.github = "vitallium/tokyonight-fish"

[yazi-plugins]
src.git = "https://github.com/yazi-rs/plugins"
fetch.git = "https://github.com/yazi-rs/plugins"

[modernx]
src.github_tag = "cyl0/ModernX"
fetch.github = "cyl0/ModernX"

[mpv-prescalers]
src.git = "https://github.com/bjin/mpv-prescalers"
fetch.git = "https://github.com/bjin/mpv-prescalers"

[plow]
src.github_tag = "six-ddc/plow"
fetch.github = "six-ddc/plow"

[p5r-grub]
src.github_tag = "SiriusAhu/Persona_5_Royal_Grub_Themes"
fetch.github = "SiriusAhu/Persona_5_Royal_Grub_Themes"

[rbutil]
src.manual = "1.5.1"
fetch.url = "https://git.rockbox.org/cgit/rockbox.git/snapshot/rockbox-rbutil_$ver.tar.gz"

[iqm]
src.git = "https://github.com/lsalzman/iqm"
fetch.git = "https://github.com/lsalzman/iqm"

[hatsune-miku-cursor]
src.git = "https://github.com/supermariofps/hatsune-miku-windows-linux-cursors"
fetch.git = "https://github.com/supermariofps/hatsune-miku-windows-linux-cursors"

[neopywal-nvim]
src.git = "https://github.com/RedsXDD/neopywal.nvim"
fetch.git = "https://github.com/RedsXDD/neopywal.nvim"

# Fonts

[ia-writer]
src.git = "https://github.com/iaolo/iA-Fonts"
fetch.git = "https://github.com/iaolo/iA-Fonts"

[sf-mono-font]
src.git = "https://github.com/supercomputra/SF-Mono-Font"
fetch.git = "https://github.com/supercomputra/SF-Mono-Font"

[sf-mono-nf-liga]
src.git = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized"
fetch.git = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized"

# Shaders

[fsrcnnx-lineart]
src.github_tag = "igv/FSRCNN-TensorFlow"
fetch.url = "https://github.com/igv/FSRCNN-TensorFlow/releases/download/$ver/checkpoints_params.7z"

[fsrcnnx8]
src.github_tag = "igv/FSRCNN-TensorFlow"
fetch.url = "https://github.com/igv/FSRCNN-TensorFlow/releases/download/$ver/FSRCNNX_x2_8-0-4-1.glsl"

[fsrcnnx16]
src.github_tag = "igv/FSRCNN-TensorFlow"
fetch.url = "https://github.com/igv/FSRCNN-TensorFlow/releases/download/$ver/FSRCNNX_x2_16-0-4-1.glsl"

[krigBilateral]
src.manual = "038064821c5f768dfc6c00261535018d5932cdd5"
fetch.url = "https://gist.githubusercontent.com/igv/a015fc885d5c22e6891820ad89555637/raw/$ver/KrigBilateral.glsl"

[ssimDownscaler]
src.manual = "575d13567bbe3caa778310bd3b2a4c516c445039"
fetch.url = "https://gist.githubusercontent.com/igv/36508af3ffc84410fe39761d6969be10/raw/$ver/SSimDownscaler.glsl"

[ssimSuperRes]
src.manual = "15d93440d0a24fc4b8770070be6a9fa2af6f200b"
fetch.url = "https://gist.githubusercontent.com/igv/2364ffa6e81540f29cb7ab4c9bc05b6b/raw/$ver/SSimSuperRes.glsl"
