# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}:
{
  acp = {
    pname = "acp";
    version = "v0.8.3";
    src = fetchFromGitHub {
      owner = "xenodium";
      repo = "acp.el";
      rev = "v0.8.3";
      fetchSubmodules = false;
      sha256 = "sha256-MX7fVVldR/du7nT+YOdSCKKKdqsr/LsfuG7uPiLN5VE=";
    };
  };
  agent-shell = {
    pname = "agent-shell";
    version = "v0.32.2";
    src = fetchFromGitHub {
      owner = "xenodium";
      repo = "agent-shell";
      rev = "v0.32.2";
      fetchSubmodules = false;
      sha256 = "sha256-ZsNb2MsrAFGilc5x/XyPFAopoJLcEmAYAAAWYbuvrMM=";
    };
  };
  artcnn = {
    pname = "artcnn";
    version = "v1.5.1";
    src = fetchFromGitHub {
      owner = "Artoriuz";
      repo = "ArtCNN";
      rev = "v1.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-NKEGTLfxM5K42C6SUY+Ot2e4iIxYmF+xL+o/XRsGd9M=";
    };
  };
  fish-catppuccin = {
    pname = "fish-catppuccin";
    version = "521560ce2075ca757473816aa31914215332bac9";
    src = fetchgit {
      url = "https://github.com/catppuccin/fish";
      rev = "521560ce2075ca757473816aa31914215332bac9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5CXdzym6Vp+FbKTVBtVdWoh3dODudADIzOLXIyIIxgQ=";
    };
    date = "2026-01-06";
  };
  fish-rose-pine = {
    pname = "fish-rose-pine";
    version = "6cfc508e81b231e955690dc9723c631374f468eb";
    src = fetchgit {
      url = "https://github.com/rose-pine/fish";
      rev = "6cfc508e81b231e955690dc9723c631374f468eb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NgfZnaik5OAur53y3WA0Hqu6f332aVdhhMWnEtDxmNs=";
    };
    date = "2026-01-27";
  };
  fish-tokyonight = {
    pname = "fish-tokyonight";
    version = "v4.8.0";
    src = fetchFromGitHub {
      owner = "vitallium";
      repo = "tokyonight-fish";
      rev = "v4.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-JI1kTez4CeMpSKcSikFUee15N48zkJJOvLHCi0H2PUc=";
    };
  };
  hatsune-miku-cursor = {
    pname = "hatsune-miku-cursor";
    version = "1.2.6";
    src = fetchFromGitHub {
      owner = "supermariofps";
      repo = "hatsune-miku-windows-linux-cursors";
      rev = "1.2.6";
      fetchSubmodules = false;
      sha256 = "sha256-OQjjOc9VnxJ7tWNmpHIMzNWX6WsavAOkgPwK1XAMwtE=";
    };
  };
  ia-writer = {
    pname = "ia-writer";
    version = "f32c04c3058a75d7ce28919ce70fe8800817491b";
    src = fetchgit {
      url = "https://github.com/iaolo/iA-Fonts";
      rev = "f32c04c3058a75d7ce28919ce70fe8800817491b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-2T165nFfCzO65/PIHauJA//S+zug5nUwPcg8NUEydfc=";
    };
    date = "2023-06-16";
  };
  iqm = {
    pname = "iqm";
    version = "8554dca2b86dc3845981fad6758d3829ce0d4a56";
    src = fetchgit {
      url = "https://github.com/lsalzman/iqm";
      rev = "8554dca2b86dc3845981fad6758d3829ce0d4a56";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-zR3AdHg0f2g14ZHVgTREYheXcHr6evnZxP3HEo7byRI=";
    };
    date = "2025-07-24";
  };
  mpv-retro-shaders = {
    pname = "mpv-retro-shaders";
    version = "f4ea211db4e2afb5f5dc5a3daf816749c9cd7f03";
    src = fetchgit {
      url = "https://github.com/hhirtz/mpv-retro-shaders";
      rev = "f4ea211db4e2afb5f5dc5a3daf816749c9cd7f03";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Y3R4GDDJl5Tles4SYRYDXnrjnKQelfXkS2g0McHLIV0=";
    };
    date = "2025-07-24";
  };
  ocenaudio-bin = {
    pname = "ocenaudio-bin";
    version = "3.17.1";
    src = fetchurl {
      url = "https://www.ocenaudio.com/downloads/index.php/ocenaudio_universal.dmg?version=v3.17.1";
      sha256 = "sha256-YM9opanJcIBh7ZNqApP/yKUfNMQ1uf5S8VucZAk1jVU=";
    };
  };
  p5r-grub = {
    pname = "p5r-grub";
    version = "v1.0";
    src = fetchFromGitHub {
      owner = "SiriusAhu";
      repo = "Persona_5_Royal_Grub_Themes";
      rev = "v1.0";
      fetchSubmodules = false;
      sha256 = "sha256-YnTBgUWWsR0W8eTtg3oa2MIXSqj7HW555xSEhV7/74w=";
    };
  };
  prchann-font-collection = {
    pname = "prchann-font-collection";
    version = "e99955f794eb1f1375a5cb677d129758f51cbc3d";
    src = fetchgit {
      url = "https://github.com/prchann/fonts";
      rev = "e99955f794eb1f1375a5cb677d129758f51cbc3d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-GlfGnaXNdvTLpwEssxzPyJwclgVi6iNp8hEGuy/rC5o=";
    };
    date = "2022-09-02";
  };
  sf-mono-font = {
    pname = "sf-mono-font";
    version = "1409ae79074d204c284507fef9e479248d5367c1";
    src = fetchgit {
      url = "https://github.com/supercomputra/SF-Mono-Font";
      rev = "1409ae79074d204c284507fef9e479248d5367c1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-3wG3M4Qep7MYjktzX9u8d0iDWa17FSXYnObSoTG2I/o=";
    };
    date = "2018-06-08";
  };
  sf-mono-nf-liga = {
    pname = "sf-mono-nf-liga";
    version = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
    src = fetchgit {
      url = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized";
      rev = "dc5a3e6fcc2e16ad476b7be3c3c17c2273b260ea";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AYjKrVLISsJWXN6Cj74wXmbJtREkFDYOCRw1t2nVH2w=";
    };
    date = "2023-07-01";
  };
  shell-maker = {
    pname = "shell-maker";
    version = "v0.84.9";
    src = fetchFromGitHub {
      owner = "xenodium";
      repo = "shell-maker";
      rev = "v0.84.9";
      fetchSubmodules = false;
      sha256 = "sha256-dXcR6Q8TykEWqHMPm2y73Kbd9cKp0ke2lpjExNb3MIo=";
    };
  };
  shflags = {
    pname = "shflags";
    version = "v1.3.0";
    src = fetchFromGitHub {
      owner = "kward";
      repo = "shflags";
      rev = "v1.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-qOFPSYglb6p8GxagXVHdJW2namUCxi3REuR55On8QEo=";
    };
  };
}
