test-key: ENC[AES256_GCM,data:lwzDvWM8TJc0Zfr4X0jRtA==,iv:T2nzW+nPcdcc/bgzdk5q6xcQ7OtjH9raZCZJXAXc8iY=,tag:8xEBLfDL7Iq4J8PnfHr4jA==,type:str]
vyprvpn-auth-user-pass: ENC[AES256_GCM,data:0z2OKNCoOEIB+EXVdMXqCw5+pSwBJzeyO5IzpAYosfkBUlvS,iv:8UBQreLSSmSpfhsDYbRmf6vU3dHxZxilsoBsW0W0o/c=,tag:dXHdQrxSomjexkpTt/lh3A==,type:str]
tailscale-auth-key: ENC[AES256_GCM,data:jzbcYbotRVMFnFfh1M4A+4kF4B61ZSmQpWy4GGipLIJKUOwTjQGiczj7RmXO+tw1vmF9tCPpXVDhUPBaDAY=,iv:e+oH5bIhZYLFcA4bJwkCnbyJv54xxzzU1vgvUL+Vztw=,tag:WxyXmR+tiWdWua202AeNXQ==,type:str]
syncthing-password: ENC[AES256_GCM,data:MnybShMU1RVdYIiEQdPM8Yg7uUQ0PwWDz7AqL3ylRqFKQnbwrF5cyvZMBZ6dkghRj/zVEO+2EU2MzoVx,iv:p39YkbWDCG3ACSDRp0recsHFu+I+mL3ecfgyIZEj+ok=,tag:glVvWd/HmOqHrAfp7oy8WQ==,type:str]
cache-priv-key: ENC[AES256_GCM,data:lKQGwDMgXOs1BGVWNeDcqsOjS0Cj3/aS3pt/tStwSUCAwP+89AOI6pNnT+VOxk/EavnXkukCPx6TUywAhdfbkce04gC5RQ2qDAuy313pC5CKUqVtXLo/DBP0MHyODGi6HQ==,iv:Cd1RjrXNXs90akp00B+iQFvVmCshvEyuG2XPV4DWqW8=,tag:p27K2ZS9gCRLN/CFXv6q3g==,type:str]
sabnzbd-username: ENC[AES256_GCM,data:x7tgKajC6g==,iv:tBW5AYWco6ynacxsszT7HXYL5PLiTcNynw1FOF5AX90=,tag:JOLVaRWVhgWuGYBg2L2sYA==,type:str]
sabnzbd-password: ENC[AES256_GCM,data:mCy+zQ4yWNT60fBfCTCZxp4lh04=,iv:ogPsUKPyQdIKtOBmrfoJ7/Vknmzo8kPLIo/KdnTdsrk=,tag:wV1F9/HbEyEDGm8H35oRag==,type:str]
sabnzbd-api-key: ENC[AES256_GCM,data:azrykgaC42XvoLY4/gjKVLpntNI5EQv7EV2h4J1kgCY=,iv:/xeHicAM5ewhToY8LgUpXCyso5EwGsfHSjXVcrsRA04=,tag:u+2BAPSV963ZXc+0+jlt1g==,type:str]
sabnzbd-nzb-key: ENC[AES256_GCM,data:YlTH3jv7X5Bv8HrrDTDawy+kft9mrt75rUEGIHUlVss=,iv:3Kg2JhGY0xNEURgcLXXhx2KYKXJSue45N81vDC9E6Ec=,tag:97hOYblpSv4tQkpdLpPObw==,type:str]
newshosting-username: ENC[AES256_GCM,data:zGNGqaLHJCoVZQE=,iv:qq2Au/X8R74C6s3T9VuwOYsiHrW7rV6AujM7E54Csww=,tag:9/ZsdaMI3/DfmwaPNxTEVw==,type:str]
newshosting-password: ENC[AES256_GCM,data:bfTvWEsSzxkXCrQoWXs=,iv:iSVq8ecOfHGfCQapE413PWQJd/X7beZY4/uETr99LVc=,tag:sRMW+DTA9a/zvTMDCNUQow==,type:str]
sops:
    age:
        - recipient: age1ln33jd2r422sf9ncryve4qv2yhp7l5w6h6nahmyxe667p0sn25pqcunuje
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcDF6b1gwUnJ3Qm1KL2Z1
            MnhCamdxR2pOU1dZeGhOMmxFYk5xWTF5U0NvCkNzZVVBdnBWaU95bk43dWt4V2tU
            c0pTTDFPNWV5Lzk0VTNGREF0cmpSckEKLS0tIGwzeGVQVUxNSklWSE9PODYyaU9P
            SzJQckhmNTZCUUN6Zi90T3NiYTB2SWcKfvf4oMN8TmbU4Xrwdpyyx8V9tecB9kqT
            LLmMDIpn8UTKa9sLNzYCXmmuvO0oQUaQF01djrJ7F3TXXNP5V6I7pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T03:59:59Z"
    mac: ENC[AES256_GCM,data:NtQynAVAaCHrgCXpdQn0JtC8hMZMuPny1lEI1hAgUJIoa9WinUZdW4Y9x8PQ0V75Czz3FtS3TeL7tqVec6X5b9HgK6syMT/LmrTUB6Acmt4zH7d2terKzCqvCJcaWv5iRV7vWJC2wgl73afkceWiKOwrUxSmI8/ypQ1xVVjPaog=,iv:ZC/iYgFv0RAu9k3NyyARMxvWzl41chq0PDLd3Qonkvo=,tag:Z6kz9mVxaYaXLsB17brYLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
